[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.0"

[context.production.environment]
  NODE_VERSION = "18.17.0"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"
